from .user_kb import (
    main_menu_kb,
    categories_kb,
    products_kb,
    product_detail_kb,
    quantity_selector_kb,
    checkout_payment_kb,
    payment_qr_kb,
    wallet_menu_kb,
    deposit_amount_presets_kb,
    deposit_qr_kb,
    orders_list_kb,
    back_to_menu_kb,
)
from .admin_kb import (
    admin_main_kb,
    admin_products_list_kb,
    admin_product_detail_kb,
    admin_orders_filter_kb,
    admin_order_actions_kb,
    admin_user_actions_kb,
    admin_coupons_kb,
    admin_settings_kb,
)

__all__ = [
    "main_menu_kb",
    "categories_kb",
    "products_kb",
    "product_detail_kb",
    "quantity_selector_kb",
    "checkout_payment_kb",
    "payment_qr_kb",
    "wallet_menu_kb",
    "deposit_amount_presets_kb",
    "deposit_qr_kb",
    "orders_list_kb",
    "back_to_menu_kb",
    "admin_main_kb",
    "admin_products_list_kb",
    "admin_product_detail_kb",
    "admin_orders_filter_kb",
    "admin_order_actions_kb",
    "admin_user_actions_kb",
    "admin_coupons_kb",
    "admin_settings_kb",
]
